# Relax this from the default of 10
Metrics/MethodLength:
  Description: 'Avoid methods longer than 15 lines of code.'
  Max: 15

# This is the Hanami generator default
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - 'apps/web/application.rb'
    - 'apps/web/views/application_layout.rb'
    - 'apps/api/application.rb'
    - 'apps/api/controllers/validation.rb'

# Almost all classes in this app are self-explanatory
Style/Documentation:
  Enabled: false
