language: ruby
sudo: false
cache: bundler

rvm:
  - 2.3.1

install: bundle install --jobs=3 --retry=3 --without production

script:
  - 'HANAMI_ENV=test bundle exec hanami db create'
  - 'HANAMI_ENV=test bundle exec hanami db migrate'
  - 'bundle exec rake test'
  - 'bundle exec rubocop'
